import cmp from './cmp.jpg';
import ss1 from './ss1.jpg';
import itera from './itera3.jpg';
import makeup from './makeup.jpg';
import seus from './seus.jpg';
import solas from './solas.jpg';
import sildurs from './sildurs.png';
import mellow from './mellow.webp';
import photon from './photon.jpg';
import lymbo from './lymbo.webp';
import Default from './Default.jpg';

export default [
    {
        id: 1,
        title: "Complementary Shaders",
        plataforma: "pc",
        descripcion: "Shader Minecraft",
        image: cmp,
        precio: 1000,
        precioCarrito:1000,
        precioOriginal:1000,
        cantidad:1,
        url:'https://www.complementary.dev/shaders/',
    },
    {
        id: 2,
        title: "BSL Shaders",
        plataforma: "pc",
        descripcion: "Shader Minecraft",
        image: ss1,
        precio: 1000,
        precioCarrito:1000,
        precioOriginal:1000,
        cantidad:1,
        url:'https://bitslablab.com/bslshaders/',
    },
    {
        id: 3,
        title: "Iteration Shaders",
        plataforma: "pc",
        descripcion: "Shader Minecraft",
        image: itera,
        precio: 1000,
        precioCarrito:1000,
        precioOriginal:1000,
        cantidad:1,
        url:'https://www.reddit.com/r/Minecraft/comments/19acyhb/minecraft_shader_iteration_t300/?rdt=43529',
    },
    {
        id: 4,
        title: "MakeUp Shaders",
        plataforma: "pc",
        descripcion: "Shader Minecraft",
        image: makeup,
        precio: 1000,
        precioCarrito:1000,
        precioOriginal:1000,
        cantidad:1,
        url:'https://zonacraft.net/makeup-shaders/',
    },
    {
        id: 5,
        title: "Seus Shaders",
        plataforma: "pc",
        descripcion: "Shader Minecraft",
        image: seus,
        precio: 1000,
        precioCarrito:1000,
        precioOriginal:1000,
        cantidad:1,
        url:'https://www.sonicether.com/seus/',
    },
    {
        id: 6,
        title: "Solas Shaders",
        plataforma: "pc",
        descripcion: "Shader Minecraft",
        image: solas,
        precio: 1000,
        precioCarrito:1000,
        precioOriginal:1000,
        cantidad:1,
        url:'https://zonacraft.net/solas-shaders-para-minecraft/',
    },
    {
        id: 7,
        title: "Sildurs Shaders",
        plataforma: "pc",
        descripcion: "Shader Minecraft",
        image: sildurs,
        precio: 1000,
        precioCarrito:1000,
        precioOriginal:1000,
        cantidad:1,
        url:'https://texture-packs.com/shaders/sildurs/',
    },
    {
        id: 8,
        title: "Mellow Shaders",
        plataforma: "pc",
        descripcion: "Shader Minecraft",
        image: mellow,
        precio: 1000,
        precioCarrito:1000,
        precioOriginal:1000,
        cantidad:1,
        url:'https://zonacraft.net/mellow-shaders/',
    },
    {
        id: 9,
        title: "Photon Shaders",
        plataforma: "pc",
        descripcion: "Shader Minecraft",
        image: photon,
        precio: 1000,
        precioCarrito:1000,
        precioOriginal:1000,
        cantidad:1,
        url:'https://zonacraft.net/photon-shaders-para-minecraft/',
    },
    {
        id: 10,
        title: "Lymbo Shaders",
        plataforma: "pc",
        descripcion: "Shader Minecraft",
        image: lymbo,
        precio: 1000,
        precioCarrito:1000,
        precioOriginal:1000,
        cantidad:1,
        url:'https://zonacraft.net/lymbo-shaders/',
    },
    {
        id: 11,
        title: "Default+ Shaders",
        plataforma: "pc",
        descripcion: "Shader Minecraft",
        image: Default,
        precio: 1000,
        precioCarrito:1000,
        precioOriginal:1000,
        cantidad:1,
        url:'https://zonacraft.net/stereos-default-shaders/',
    },
]